[package]
name = "rosenv"
version = "0.1.0"
edition = "2021"
authors = ["Alvaro"]
description = "ROS 2 distribution environment manager"

[dependencies]
clap = { version = "4.5", features = ["derive", "cargo"] }
anyhow = "1.0"
dirs = "5.0"
